##Coding the attention 

In [2]:
import torch

In [3]:
inputs = torch.tensor(
        [[0.43, 0.15, 0.89], # Your (x^1)
        [0.55, 0.87, 0.66], # journey (x^2)
        [0.57, 0.85, 0.64], # starts (x^3)
        [0.22, 0.58, 0.33], # with (x^4)
        [0.77, 0.25, 0.10], # one (x^5)
        [0.05, 0.80, 0.55]] # step (x^6)
)

In [4]:
print(inputs)
query = inputs[1]

print(query)


tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])
tensor([0.5500, 0.8700, 0.6600])


In [5]:
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [6]:
attn_weights_2_tmp = attn_scores_2/attn_scores_2.sum()
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum: tensor(1.0000)


In [7]:
def softmax_naive(x):
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_2_naive = softmax_naive(attn_scores_2)
print("Attention weights:", attn_weights_2_naive)
print("Sum:", attn_weights_2_naive.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [8]:
#Pythorch softmax
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Attention weights:", attn_weights_2)
print("Sum:", attn_weights_2.sum())

Attention weights: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum: tensor(1.)


In [9]:
print(inputs[0])

tensor([0.4300, 0.1500, 0.8900])


In [10]:
query = inputs[1] #2nd input token is the query
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i
    print(i, ":  attn_weights_2[i] * x_i =  context_vec_2", attn_weights_2[i],  x_i, context_vec_2)

#multiplying each input row with corresponding attention weight and summing them up
print("Context Vector for input 2 :",context_vec_2)

0 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.1385) tensor([0.4300, 0.1500, 0.8900]) tensor([0.0596, 0.0208, 0.1233])
1 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.2379) tensor([0.5500, 0.8700, 0.6600]) tensor([0.1904, 0.2277, 0.2803])
2 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.2333) tensor([0.5700, 0.8500, 0.6400]) tensor([0.3234, 0.4260, 0.4296])
3 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.1240) tensor([0.2200, 0.5800, 0.3300]) tensor([0.3507, 0.4979, 0.4705])
4 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.1082) tensor([0.7700, 0.2500, 0.1000]) tensor([0.4340, 0.5250, 0.4813])
5 :  attn_weights_2[i] * x_i =  context_vec_2 tensor(0.1581) tensor([0.0500, 0.8000, 0.5500]) tensor([0.4419, 0.6515, 0.5683])
Context Vector for input 2 : tensor([0.4419, 0.6515, 0.5683])


##3.3.2 Computing attention weights for all input tokens


In [12]:
attn_scores = torch.empty(6,6)
print(attn_scores)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [16]:
print(inputs)

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])


In [15]:
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i,j] = torch.dot(x_i, x_j)
        print(i, j, x_i, x_j, attn_scores[i,j])

print(attn_scores)

0 0 tensor([0.4300, 0.1500, 0.8900]) tensor([0.4300, 0.1500, 0.8900]) tensor(0.9995)
0 1 tensor([0.4300, 0.1500, 0.8900]) tensor([0.5500, 0.8700, 0.6600]) tensor(0.9544)
0 2 tensor([0.4300, 0.1500, 0.8900]) tensor([0.5700, 0.8500, 0.6400]) tensor(0.9422)
0 3 tensor([0.4300, 0.1500, 0.8900]) tensor([0.2200, 0.5800, 0.3300]) tensor(0.4753)
0 4 tensor([0.4300, 0.1500, 0.8900]) tensor([0.7700, 0.2500, 0.1000]) tensor(0.4576)
0 5 tensor([0.4300, 0.1500, 0.8900]) tensor([0.0500, 0.8000, 0.5500]) tensor(0.6310)
1 0 tensor([0.5500, 0.8700, 0.6600]) tensor([0.4300, 0.1500, 0.8900]) tensor(0.9544)
1 1 tensor([0.5500, 0.8700, 0.6600]) tensor([0.5500, 0.8700, 0.6600]) tensor(1.4950)
1 2 tensor([0.5500, 0.8700, 0.6600]) tensor([0.5700, 0.8500, 0.6400]) tensor(1.4754)
1 3 tensor([0.5500, 0.8700, 0.6600]) tensor([0.2200, 0.5800, 0.3300]) tensor(0.8434)
1 4 tensor([0.5500, 0.8700, 0.6600]) tensor([0.7700, 0.2500, 0.1000]) tensor(0.7070)
1 5 tensor([0.5500, 0.8700, 0.6600]) tensor([0.0500, 0.8000, 0.55

In [ ]:
#for loops are slow, we can use mat mul
attn_scores = inputs @ inputs.T #matrix multiplication , T is transpose
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [18]:
attn_weights = torch.softmax(attn_scores, dim=1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [20]:
row_2_sum = sum([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
print("Row 2 sum:", row_2_sum)
print("All row sums:", attn_weights.sum(dim=1))

Row 2 sum: 1.0
All row sums: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [21]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


In [22]:
print("Previous 2nd context vector:", context_vec_2)


Previous 2nd context vector: tensor([0.4419, 0.6515, 0.5683])
